package com.mohmk10.audittrail.admin.domain;

public enum Permission {
    EVENTS_READ, EVENTS_WRITE,
    SEARCH_READ,
    REPORTS_READ, REPORTS_WRITE,
    RULES_READ, RULES_WRITE,
    ALERTS_READ, ALERTS_WRITE,
    SOURCES_READ, SOURCES_WRITE,
    API_KEYS_READ, API_KEYS_WRITE,
    USERS_READ, USERS_WRITE,
    TENANT_SETTINGS
}
